In [1]:
from docling.document_converter import DocumentConverter

# source = "https://arxiv.org/pdf/2408.09869"  # PDF path or URL
# source = "https://arxiv.org/pdf/2312.11521" 

source = "https://s203.q4cdn.com/667520861/files/doc_financials/2025/q4/RBRK-4Q25-Investor-Presentation-1.pdf" 
converter = DocumentConverter()
result = converter.convert(source)
# print(result.document.export_to_markdown())  # output: "### Docling Technical Report[...]"

/Users/tatsa/miniforge3/envs/docling/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/Users/tatsa/miniforge3/envs/docling/lib/python3.11/site-packages/torch/utils/data/dataloader.py:683: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/tatsa/miniforge3/envs/docling/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/tatsa/miniforge3/envs/docling/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/Users/tatsa/miniforge3/envs/docling/lib/python3.11/site-packages/docling/pipeline/standard_pdf_pipeline.py:262: RuntimeWarning: Mean of empty slice
  np.nanmean(

In [20]:
from docling.datamodel.base_models import InputFormat
from docling.datamodel.pipeline_options import EasyOcrOptions, PdfPipelineOptions
from docling.document_converter import DocumentConverter, PdfFormatOption

artifacts_path = "/Users/tatsa/.cache/docling/models"
source = "https://assets.accessible-digital-documents.com/uploads/2017/01/sample-tables.pdf"

pipeline_options = PdfPipelineOptions(artifacts_path=artifacts_path)
doc_converter = DocumentConverter(
    format_options={
        InputFormat.PDF: PdfFormatOption(pipeline_options=pipeline_options)
    }
)

In [3]:
result = doc_converter.convert(source)
# print(result.document.export_to_markdown())

/Users/tatsa/miniforge3/envs/docling/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/tatsa/miniforge3/envs/docling/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/Users/tatsa/miniforge3/envs/docling/lib/python3.11/site-packages/docling/pipeline/standard_pdf_pipeline.py:262: RuntimeWarning: Mean of empty slice
  np.nanmean(
/Users/tatsa/miniforge3/envs/docling/lib/python3.11/site-packages/docling/pipeline/standard_pdf_pipeline.py:267: RuntimeWarning: Mean of empty slice
  np.nanmean(

In [11]:
import logging
import time
from pathlib import Path
import pandas as pd
from docling.document_converter import DocumentConverter
_log = logging.getLogger(__name__)

logging.basicConfig(level=logging.INFO)

# input_doc_path = Path("./tests/data/pdf/2206.01062.pdf")
output_dir = Path("scratch")

#doc_converter = DocumentConverter()

start_time = time.time()

conv_res = doc_converter.convert(source)

INFO:docling.document_converter:Going to convert document batch...
INFO:docling.pipeline.base_pipeline:Processing document sample-tables.pdf
/Users/tatsa/miniforge3/envs/docling/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/tatsa/miniforge3/envs/docling/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/Users/tatsa/miniforge3/envs/docling/lib/python3.11/site-packages/docling/pipeline/standard_pdf_pipeline.py:262: RuntimeWarning: Mean of empty slice
  np.nanmean(
/Users/tatsa/miniforge3/envs/docling/lib/python3.11/site-packages/docling/pipeline/standard_pdf_pipeline.py:267: RuntimeWarning: Mean of empty slice
  np.nanmean(
INFO:docling.document_converter:Finished converting document sample-tables.pdf in 16.37 sec.

In [ ]:
output_dir.mkdir(parents=True, exist_ok=True)

doc_filename = conv_res.input.file.stem

# Export tables
for table_ix, table in enumerate(conv_res.document.tables):
    table_df: pd.DataFrame = table.export_to_dataframe()
    print(f"## Table {table_ix}")
    print(table_df.to_markdown())

    # Save the table as csv
    element_csv_filename = output_dir / f"{doc_filename}-table-{table_ix + 1}.csv"
    _log.info(f"Saving CSV table to {element_csv_filename}")
    table_df.to_csv(element_csv_filename)

    # Save the table as html
    element_html_filename = output_dir / f"{doc_filename}-table-{table_ix + 1}.html"
    _log.info(f"Saving HTML table to {element_html_filename}")
    with element_html_filename.open("w") as fp:
        fp.write(table.export_to_html(doc=conv_res.document))

end_time = time.time() - start_time

# _log.info(f"Document converted and tables exported in {end_time:.2f}

INFO:docling.document_converter:Going to convert document batch...
INFO:docling.document_converter:Initializing pipeline for StandardPdfPipeline with options hash c499d9f86077c60ffc093a8b3df8b189
INFO:docling.utils.accelerator_utils:Accelerator device: 'mps'
INFO:docling.utils.accelerator_utils:Accelerator device: 'mps'
INFO:docling.utils.accelerator_utils:Accelerator device: 'mps'
INFO:docling.pipeline.base_pipeline:Processing document sample-tables.pdf
/Users/tatsa/miniforge3/envs/docling/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/tatsa/miniforge3/envs/docling/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/Users/tatsa/miniforge3/envs/docling/lib/python3.11/site-packages/docling/pipeline/standard_pdf_pipeline.py:262: RuntimeWarning: Mean of empty slice
  np.nanmean(
/Users/tatsa/miniforge3/envs/docling/lib/python3.11/site-packages/docling/pipeline/standard_pdf_pipeline.py:267: RuntimeWarning: Mean of empty slice
  np.nanmean(
INFO:docling.document_converter:Finished converting document sample-tables.pdf in 18.45 sec.
INFO:__main__:Saving CSV table to scratch/sample-tables-table-1.csv
INFO:__main__:Saving HTML table to scratch/sample-tables-table-1.html
INFO:__main__:Saving CSV table to scratch/sample-tables-table-2.csv
INFO:__main__:Saving HTML table to scratch/sample-tables-table-2.html
INFO:__main__:Saving CSV table to scratch/sample-tables-table-3.csv
INFO:__main__:Saving HTML table to scratch/sample-tables-table-3.html
INFO:__main__:Saving CSV table to scratch/sample-tables-table-4.csv
INFO:__main__:Saving HTML table to scratch/sample-tables-table-4.html
INFO:__main__:Saving CSV table to scratch/sample-tables-table-5.csv
INFO:__main__:Saving HTML table to scratch/sample-tables-table-5.html
INFO:__main__:Saving CSV table to scratch/sample-tables-table-6.csv
INFO:__main__:Saving HTML table to scratch/sample-tables-table-6.html
INFO:__main__:Saving CSV table to scratch/sample-tables-table-7.csv
INFO:__main__:Saving HTML table to scratch/sample-tables-table-7.html
INFO:__main__:Saving CSV table to scratch/sample-tables-table-8.csv
INFO:__main__:Saving HTML table to scratch/sample-tables-table-8.html
INFO:__main__:Saving CSV table to scratch/sample-tables-table-9.csv
INFO:__main__:Saving HTML table to scratch/sample-tables-table-9.html
INFO:__main__:Saving CSV table to scratch/sample-tables-table-10.csv
INFO:__main__:Saving HTML table to scratch/sample-tables-table-10.html
INFO:__main__:Saving CSV table to scratch/sample-tables-table-11.csv
INFO:__main__:Saving HTML table to scratch/sample-tables-table-11.html
INFO:__main__:Saving CSV table to scratch/sample-tables-table-12.csv
INFO:__main__:Saving HTML table to scratch/sample-tables-table-12.html
INFO:__main__:Saving CSV table to scratch/sample-tables-table-13.csv
INFO:__main__:Saving HTML table to scratch/sample-tables-table-13.html
INFO:__main__:Saving CSV table to scratch/sample-tables-table-14.csv
INFO:__main__:Saving HTML table to scratch/sample-tables-table-14.html
INFO:__main__:Saving CSV table to scratch/sample-tables-table-15.csv
INFO:__main__:Saving HTML table to scratch/sample-tables-table-15.html
INFO:__main__:Saving CSV table to scratch/sample-tables-table-16.csv
INFO:__main__:Saving HTML table to scratch/sample-tables-table-16.html
INFO:__main__:Saving CSV table to scratch/sample-tables-table-17.csv
INFO:__main__:Saving HTML table to scratch/sample-tables-table-17.html
INFO:__main__:Saving CSV table to scratch/sample-tables-table-18.csv
INFO:__main__:Saving HTML table to scratch/sample-tables-table-18.html
INFO:__main__:Saving CSV table to scratch/sample-tables-table-19.csv
INFO:__main__:Saving HTML table to scratch/sample-tables-table-19.html
INFO:__main__:Saving CSV table to scratch/sample-tables-table-20.csv
INFO:__main__:Saving HTML table to scratch/sample-tables-table-20.html
INFO:__main__:Saving CSV table to scratch/sample-tables-table-21.csv
INFO:__main__:Saving HTML table to scratch/sample-tables-table-21.html
INFO:__main__:Saving CSV table to scratch/sample-tables-table-22.csv
INFO:__main__:Saving HTML table to scratch/sample-tables-table-22.html
INFO:__main__:Saving CSV table to scratch/sample-tables-table-23.csv
INFO:__main__:Saving HTML table to scratch/sample-tables-table-23.html
INFO:__main__:Saving CSV table to scratch/sample-tables-table-24.csv
INFO:__main__:Saving HTML table to scratch/sample-tables-table-24.html
INFO:__main__:Saving CSV table to scratch/sample-tables-table-25.csv
INFO:__main__:Saving HTML table to scratch/sample-tables-table-25.html
INFO:__main__:Saving CSV table to scratch/sample-tables-table-26.csv
INFO:__main__:Saving HTML table to scratch/sample-tables-table-26.html
INFO:__main__:Saving CSV table to scratch/sample-tables-table-27.csv
INFO:__main__:Saving HTML table to scratch/sample-tables-table-27.html
INFO:__main__:Saving CSV table to scratch/sample-tables-table-28.csv
INFO:__main__:Saving HTML table to scratch/sample-tables-table-28.html
INFO:__main__:Saving CSV table to scratch/sample-tables-table-29.csv
INFO:__main__:Saving HTML table to scratch/sample-tables-table-29.html

## Table 0
|    | Column header (TH)   | Column header (TH)   | Column header (TH)   |
|---:|:---------------------|:---------------------|:---------------------|
|  0 | Data cell (TD)       | Data cell (TD)       | Row header (TH)      |
|  1 | Data cell (TD)       | Data cell (TD)       | Row header(TH)       |
## Table 1
|    | Expenditure by function £ million   | Expenditure by function £ million   |   2009/10 |   2010/11 1 |
|---:|:------------------------------------|:------------------------------------|----------:|------------:|
|  0 | Policy functions                    | Financial                           |     22.5  |       30.57 |
|  1 | Policy functions                    | Information 2                       |     10.2  |       14.8  |
|  2 | Policy functions                    | Contingency                         |      2.6  |        1.2  |
|  3 | Remunerated functions               | Agency services 3                   |     44.7  |       35.91 |
|  4 | Remunerated functions               | Payments                            |     22.41 |       19.88 |
|  5 | Remunerated functions               | Banking                             |     22.9  |       44.23 |
|  6 | Remunerated functions               | Other                               |     12.69 |       10.32 |
## Table 2
|    | 0                | 1              |
|---:|:-----------------|:---------------|
|  0 | Daniel Radcliffe | Main character |
|  1 | Rupert Grint     | Sidekick 1     |
|  2 | Emma Watson      | Sidekick 2     |
|  3 | Robbie Coltrane  | Lovable ogre   |
|  4 | Maggie Smith     | Professor      |
|  5 | Richard Harris   | Headmaster     |
## Table 3
|    | Role             | Actor          |
|---:|:-----------------|:---------------|
|  0 | Daniel Radcliffe | Main character |
|  1 | Rupert Grint     | Sidekick 1     |
|  2 | Emma Watson      | Sidekick 2     |
|  3 | Robbie Coltrane  | Lovable ogre   |
|  4 | Maggie Smith     | Professor      |
|  5 | Richard Harris   | Headmaster     |
## Table 4
|    |                             | 2010   | 2009   | 2008   |
|---:|:----------------------------|:-------|:-------|:-------|
|  0 | Non-current assets          |        |        |        |
|  1 | Property                    | 345    | 445    | 222    |
|  2 | Investment                  | 567    | 654    | 423    |
|  3 | Intangibles                 | 423    | 123    | 453    |
|  4 | Current assets              |        |        |        |
|  5 | Trade and other receivables | 435    | 634    | 231    |
|  6 | Cash and cash equivalents   | 524    | 123    | 482    |
|  7 | Other                       | 223    | 211    | 254    |
## Table 5
|    | Rainfall (inches)   | Americas   |   Asia |   Europe |   Africa |
|---:|:--------------------|:-----------|-------:|---------:|---------:|
|  0 | 2010                | 2010       |   2010 |     2010 |     2010 |
|  1 | Average             | 104        |    201 |      193 |      144 |
|  2 | 24 hour high        | 15         |     26 |       27 |       18 |
|  3 | 12 hour high        | 9          |     10 |       11 |       12 |
|  4 | 2009                | 2009       |   2009 |     2009 |     2009 |
|  5 | Average 133         |            |    244 |      155 |      166 |
|  6 | 24 hour high        | 27         |     28 |       29 |       20 |
|  7 | 12 hour high        | 11         |     12 |       13 |       16 |
## Table 6
|    | Non-current assets   |   2010 |   2009 |   2008 |
|---:|:---------------------|-------:|-------:|-------:|
|  0 | Property             |    345 |    445 |    222 |
|  1 | Investment           |    567 |    654 |    423 |
|  2 | Intangibles          |    423 |    123 |    453 |
## Table 7
|    | Current assets   |   2010 |   2009 | 2008                            |
|---:|:-----------------|-------:|-------:|:--------------------------------|
|  0 |                  |    435 |    634 | Trade and other receivables 231 |
|  1 | Cash and         |    524 |    123 | cash equivalents 482            |
|  2 | Other            |    223 |    211 | 254                             |
## Table 8
|    | Rainfall (inches)   |   Americas |   Asia |   Europe |   Africa |
|---:|:--------------------|-----------:|-------:|---------:|---------:|
|  0 | Average             |        133 |    244 |      155 |      166 |
|  1 | 24 hour high        |         27 |     28 |       29 |       20 |
|  2 | 12 hour high        |         11 |     12 |       13 |       16 |
## Table 9
|    |                        | 2011      | 2011    | 2010 restated   | 2010 restated   |
|---:|:-----------------------|:----------|:--------|:----------------|:----------------|
|  0 | General income         |           | 250,000 |                 | 200,000         |
|  1 | Increase in value, WIP |           | 15,000  |                 | 30,000          |
|  2 |                        |           | 265,000 |                 | 230,000         |
|  3 | Administrative costs   |           |         |                 |                 |
|  4 | Staff costs            | (200,000) |         | (150,000)       |                 |
|  5 | Early departures       | (10,000)  |         | (20,000)        |                 |
|  6 | Other                  | (25,000)  |         | (10,000)        |                 |
|  7 | Depreciation           | (10,000)  |         | (10,000)        |                 |
|  8 | Programme costs        |           |         |                 |                 |
|  9 | Impairment loss        | (10,000)  |         | (5,000)         |                 |
| 10 | Other                  | (5,000)   |         | (5,000)         |                 |
| 11 |                        | (260,000) |         | (200,000)       |                 |
| 12 | Surplus                |           | 5,000   |                 | 30,000          |
## Table 10
|    |                      |                       | 2011      | 2010 restated   |
|---:|:---------------------|:----------------------|:----------|:----------------|
|  0 | Income               | General income        | 250,000   | 200,000         |
|  1 |                      | Increase in value     | 15,000    | 30,000          |
|  2 |                      | Total income          | 265,000   | 230,000         |
|  3 | Administrative costs | Staff costs           | (200,000) | (150,000)       |
|  4 |                      | Early departures      | (10,000)  | (20,000)        |
|  5 |                      | Other operating costs | (25,000)  | (10,000)        |
|  6 |                      | Depreciation          | (10,000)  | (10,000)        |
|  7 | Programme costs      | Impairment loss       | (10,000)  | (5,000)         |
|  8 |                      | Other                 | (5,000)   | (5,000)         |
|  9 |                      | Total costs           | (260,000) | (200,000)       |
| 10 | Surplus              | Surplus               | 5,000     | 30,000          |
## Table 11
|    | Name   | 2008.Yes                                                       | 2008.No                                                        | 2009.Yes                                                    | 2009.No                                                     |
|---:|:-------|:---------------------------------------------------------------|:---------------------------------------------------------------|:------------------------------------------------------------|:------------------------------------------------------------|
|  0 | Bob    | 2                                                              | 5                                                              | 6                                                           | 7                                                           |
|  1 | Sue    | 3                                                              | 8                                                              | 4                                                           | 7                                                           |
|  2 | Sam    | [data relating to both columns in a single cell spanning both] | [data relating to both columns in a single cell spanning both] | [data relating to both columns a single cell spanning both] | [data relating to both columns a single cell spanning both] |
## Table 12
|    | Question                       | Respondent A   | Respondent B   | Respondent C                  |
|---:|:-------------------------------|:---------------|:---------------|:------------------------------|
|  0 |                               |                |               | Are you a UK citizen?        |
|  1 |                               |                |               | Are you currently employed?  |
|  2 | Do you have a driving licence? |               |               |                              |
## Table 13
|    | Question                       | Respondent A   | Respondent B   | Respondent C                    |
|---:|:-------------------------------|:---------------|:---------------|:--------------------------------|
|  0 | Are you a UK citizen? No       |                | Yes            | No                              |
|  1 |                                | Yes            | No             | Are you currently employed? Yes |
|  2 | Do you have a driving licence? | No             | No             | Yes                             |
## Table 14
|    |                         | 2006   | 2007   | 2008   | 2009   |
|---:|:------------------------|:-------|:-------|:-------|:-------|
|  0 | Economics               | A, B   | A, C   | A, B   | A, C   |
|  1 | International relations | A, E   | A, E   | A, B   | A, E   |
|  2 | Philosophy              | A      | A      | A      | A, D   |
|  3 | Politics                | A, D   | A, D   | A, D   | A      |
|  4 | Mathematics             | B, C   | B      | A, E   | A, B   |
|  5 | English                 | A, C   | A, B   | A,B    | C      |
## Table 15
|    |                         | 2006   | 2007   | 2008   | 2009   |
|---:|:------------------------|:-------|:-------|:-------|:-------|
|  0 | Economics               | No     | Yes    | Yes    | Yes    |
|  1 | International relations | No     | No     | No     | No     |
|  2 | Philosophy              | No     | No     | No     | No     |
|  3 | Politics                | No     | No     | No     | No     |
|  4 | Mathematics             | Yes    | No     | No     | No     |
|  5 | English                 | Yes    | Yes    | Yes    | Yes    |
## Table 16
|    | Accounting item      | Accounting item        | 2011    |
|---:|:---------------------|:-----------------------|:--------|
|  0 | Income               | General income         | 200,000 |
|  1 |                      | Increase in value, WIP | 30,000  |
|  2 |                      | Income subtotal        | 230,000 |
|  3 | Administrative costs | Staff                  | 150,000 |
|  4 |                      | Early departures       | 20,000  |
|  5 |                      | Other operating costs  | 10,000  |
|  6 |                      | Depreciation           | 10,000  |
|  7 | Programme costs      | Impairment loss        | 10,000  |
|  8 |                      | Costs subtotal         | 200,000 |
|  9 | Balance              | Balance                | 30,000  |
## Table 17
|    | Accounting item      | Accounting item        | 2011      |
|---:|:---------------------|:-----------------------|:----------|
|  0 | Income               | General income         | 200,000   |
|  1 |                      | Increase in value, WIP | 30,000    |
|  2 |                      | Income subtotal        | 230,000   |
|  3 | Administrative costs | Staff                  | (150,000) |
|  4 |                      | Early departures       | (20,000)  |
|  5 |                      | Other operating costs  | (10,000)  |
|  6 |                      | Depreciation           | (10,000)  |
|  7 | Programme costs      | Impairment loss        | (10,000)  |
|  8 |                      | Costs subtotal         | (200,000) |
|  9 | Balance              | Balance                | 30,000    |
## Table 18
|    | Country     | 1980   | 1990   |   2000 |   2010 |
|---:|:------------|:-------|:-------|-------:|-------:|
|  0 | Afghanistan | 0.78   | 1.48   |   2.16 |   3.33 |
|  1 | Albania     | 8.89   | 9.67   |   9.89 |  10.38 |
|  2 | Algeria     | 4.74   | 3.33   |   5.5  |   7.24 |
|  3 | Andorra     | 4.98   | 5.63   |   9.09 |  10.35 |
|  4 | Angola      | -      | -      |   4.42 |   4.42 |
## Table 19
|    | Expenditure by function £million   | Expenditure by function £million   |   2009/10 |   2010/11 1 |
|---:|:-----------------------------------|:-----------------------------------|----------:|------------:|
|  0 | Policy functions                   | Financial                          |     22.5  |       30.57 |
|  1 | Policy functions                   | Information 2                      |     10.2  |       14.8  |
|  2 | Policy functions                   | Contingency                        |      2.6  |        1.2  |
|  3 | Remunerated functions              | Agency services 3                  |     44.7  |       35.91 |
|  4 | Remunerated functions              | Payments                           |     22.41 |       19.88 |
|  5 | Remunerated functions              | Banking                            |     22.9  |       44.23 |
|  6 | Remunerated functions              | Other                              |     12.69 |       10.32 |
## Table 20
|    | Expenditure by function £million   | Expenditure by function £million   |   2009/10 |   2010/11 |
|---:|:-----------------------------------|:-----------------------------------|----------:|----------:|
|  0 | Policy functions                   | Financial                          |     22.5  |     30.57 |
|  1 | Policy functions                   | Information                        |     10.2  |     14.8  |
|  2 | Policy functions                   | Contingency                        |      2.6  |      1.2  |
|  3 | Remunerated functions              | Agency services                    |     44.7  |     35.91 |
|  4 | Remunerated functions              | Payments                           |     22.41 |     19.88 |
|  5 | Remunerated functions              | Banking                            |     22.9  |     44.23 |
|  6 | Remunerated functions              | Other                              |     12.69 |     10.32 |
## Table 21
|    | Expenditure £m.   | Notes.(Notes located on page [n])   |   2010. |   2011. |
|---:|:------------------|:------------------------------------|--------:|--------:|
|  0 | Information       | 1                                   |   10.2  |   14.8  |
|  1 | Contingency       |                                     |    2.6  |    1.2  |
|  2 | Payments          | 3                                   |   22.41 |   19.88 |
|  3 | Banking services  | 4                                   |   22.9  |   44.23 |
|  4 | Interest          |                                     |    0.23 |    0.1  |
|  5 | Dividends         | 23                                  |    2.5  |    3.68 |
|  6 | Other             | 9                                   |   12.69 |   10.32 |
## Table 22
|    | Name   |   2008.Entered |   2008.Completed |   2009.Entered |   2009.Completed |
|---:|:-------|---------------:|-----------------:|---------------:|-----------------:|
|  0 | Bob    |             22 |               21 |             20 |               19 |
|  1 | Sue    |             44 |               12 |             12 |               10 |
## Table 23
|    |                     | 2010   | 2009   | 2008   |
|---:|:--------------------|:-------|:-------|:-------|
|  0 | Non-current assets  |        |        |        |
|  1 | Buildings           | 345    | 445    | 222    |
|  2 | Investment          | 567    | 654    | 423    |
|  3 | Intangibles         | 423    | 123    | 453    |
|  4 | Current assets      |        |        |        |
|  5 | Trade               | 435    | 634    | 231    |
|  6 | Cash                | 524    | 123    | 482    |
|  7 | Other               | 223    | 211    | 254    |
|  8 | Current liabilities |        |        |        |
|  9 | Trade liabilities   | 154    | 125    | 421    |
| 10 | Financial debt      | 231    | 474    | 572    |
| 11 | Provisions          | 111    | 312    | 347    |
## Table 24
|    | Name   |   2008.Entered |   2008.Won |   2009.Entered |   2009.Won |
|---:|:-------|---------------:|-----------:|---------------:|-----------:|
|  0 | Bob    |             22 |         21 |             20 |         19 |
|  1 | Sue    |             44 |         12 |             12 |         10 |
|  2 | Sam    |             16 |          4 |             45 |         30 |
## Table 25
|    |                         | 2006   | 2007   | 2008   | 2009   |
|---:|:------------------------|:-------|:-------|:-------|:-------|
|  0 | Economics               | A, B   | A, C   | A, C   | A, C   |
|  1 | International relations | A, E   | A, E   | A, B   | A, B   |
|  2 | Philosophy              | A      | A      | A      | A      |
|  3 | Politics                | A, D   | A, D   | A, B   | A      |
|  4 | Mathematics             | B, C   | B      | A, B   | A, B   |
|  5 | English                 | A, C   | A, B   | A,B    | A, C   |
## Table 26
|    |   Name |   Apples | Pears                                |
|---:|-------:|---------:|:-------------------------------------|
|  0 |     20 |       25 | Bob Scott                            |
|  1 |     24 |       15 | Susan. P. Arnold-Jones, BA, FRSA, MD |
|  2 |     14 |       10 | Sam Holder-Dickinson                 |
## Table 27
|    |                     | 2010   | 2009   | 2008   |
|---:|:--------------------|:-------|:-------|:-------|
|  0 | Non-current assets  |        |        |        |
|  1 | Buildings           | 345    | 445    | 222    |
|  2 | Investment          | 567    | 654    | 423    |
|  3 | Intangibles         | 423    | 123    | 453    |
|  4 | Current assets      |        |        |        |
|  5 | Trade               | 435    | 634    | 231    |
|  6 | Cash                | 524    | 123    | 482    |
|  7 | Other               | 223    | 211    | 254    |
|  8 | Current liabilities |        |        |        |
|  9 | Trade liabilities   | 154    | 125    | 421    |
| 10 | Financial debt      | 231    | 474    | 572    |
| 11 | Provisions          | 111    | 312    | 347    |
## Table 28
|    |                     |   South America |   Asia |   Africa |   Australia |
|---:|:--------------------|----------------:|-------:|---------:|------------:|
|  0 | 2010                |          2010   | 2010   |   2010   |      2010   |
|  1 | Highest average     |           523.6 |  467.4 |    405   |       340.5 |
|  2 | Highest in 24 hours |            73.1 |   54.1 |     27.2 |        66.3 |
|  3 | Highest in 12 hours |            42.4 |   30.1 |     15.9 |        40.3 |
|  4 | 2009                |          2009   | 2009   |   2009   |      2009   |
|  5 | Highest average     |           487.7 |  453.6 |    398.7 |       356   |
|  6 | Highest in 24 hours |            67.2 |   53.2 |     44.3 |        53.8 |
|  7 | Highest in 12 hours |            34.7 |   34.1 |     29.8 |        31   |
|  8 | 2008                |          2008   | 2008   |   2008   |      2008   |
|  9 | Highest average     |           496.7 |  444.3 |    502.1 |       399.6 |
| 10 | Highest in 24 hours |            44.2 |   56.7 |     32.1 |        63.2 |
| 11 | Highest in 12 hours |            30.1 |   32.7 |     21.9 |        40.2 |

In [14]:
import logging
import time
from pathlib import Path

In [15]:
from docling_core.types.doc import ImageRefMode, PictureItem, TableItem

In [16]:
from docling.datamodel.base_models import InputFormat
from docling.datamodel.pipeline_options import PdfPipelineOptions
from docling.document_converter import DocumentConverter, PdfFormatOption

In [17]:
IMAGE_RESOLUTION_SCALE = 2.0

In [23]:
logging.basicConfig(level=logging.INFO)

# input_doc_path = Path("https://s203.q4cdn.com/667520861/files/doc_financials/2026/q1/RBRK-1Q26-Investor-Presentation-Final.pdf")
output_dir = Path("scratch")

source = "https://s203.q4cdn.com/667520861/files/doc_financials/2026/q1/RBRK-1Q26-Investor-Presentation-Final.pdf"

# Important: For operating with page images, we must keep them, otherwise the DocumentConverter
# will destroy them for cleaning up memory.
# This is done by setting PdfPipelineOptions.images_scale, which also defines the scale of images.
# scale=1 correspond of a standard 72 DPI image
# The PdfPipelineOptions.generate_* are the selectors for the document elements which will be enriched
# with the image field
pipeline_options = PdfPipelineOptions()
pipeline_options.images_scale = IMAGE_RESOLUTION_SCALE
pipeline_options.generate_page_images = True
pipeline_options.generate_picture_images = True

# doc_converter = DocumentConverter(
#     format_options={
#         InputFormat.PDF: PdfFormatOption(pipeline_options=pipeline_options)
#     }
# )

start_time = time.time()

conv_res = doc_converter.convert(source)

INFO:docling.document_converter:Going to convert document batch...
INFO:docling.pipeline.base_pipeline:Processing document RBRK-1Q26-Investor-Presentation-Final.pdf
/Users/tatsa/miniforge3/envs/docling/lib/python3.11/site-packages/torch/utils/data/dataloader.py:683: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/tatsa/miniforge3/envs/docling/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/tatsa/miniforge3/envs/docling/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/Users/tatsa/miniforge3/envs/docling/lib/python3.11/site-packages/docling/pipeline/standard_pdf_pipeline.py:262: RuntimeWarning: Mean of empty slice
  np.nanmean(
INFO:docling.document_converter:Finished converting document RBRK-1Q26-Investor-Presentation-Final.pdf in 29.85 sec.

In [27]:
output_dir.mkdir(parents=True, exist_ok=True)
doc_filename = conv_res.input.file.stem

# Save page images
for page_no, page in conv_res.document.pages.items():
    page_no = page.page_no
    page_image_filename = output_dir / f"{doc_filename}-{page_no}.png"
    # with page_image_filename.open("wb") as fp:
    #     page.image.pil_image.save(fp, format="PNG")

# Save images of figures and tables
table_counter = 0
picture_counter = 0
for element, _level in conv_res.document.iterate_items():
    if isinstance(element, TableItem):
        table_counter += 1
        element_image_filename = (
            output_dir / f"{doc_filename}-table-{table_counter}.png"
        )
        # with element_image_filename.open("wb") as fp:
        #     element.get_image(conv_res.document).save(fp, "PNG")

    if isinstance(element, PictureItem):
        picture_counter += 1
        element_image_filename = (
            output_dir / f"{doc_filename}-picture-{picture_counter}.png"
        )
        # with element_image_filename.open("wb") as fp:
        #     element.get_image(conv_res.document).save(fp, "PNG")

# Save markdown with embedded pictures
md_filename = output_dir / f"{doc_filename}-with-images.md"
conv_res.document.save_as_markdown(md_filename, image_mode=ImageRefMode.EMBEDDED)

# Save markdown with externally referenced pictures
md_filename = output_dir / f"{doc_filename}-with-image-refs.md"
conv_res.document.save_as_markdown(md_filename, image_mode=ImageRefMode.REFERENCED)

# Save HTML with externally referenced pictures
html_filename = output_dir / f"{doc_filename}-with-image-refs.html"
conv_res.document.save_as_html(html_filename, image_mode=ImageRefMode.REFERENCED)

end_time = time.time() - start_time

    #_log.info(f"Document converted and figures exported in {end_time:.2f} seconds.")